Feature/70043358
EntrevistadorInteligente/si-client-app pull request #72
Opened 2024-07-27 02:59 UTC by DylanSerkovich

## 📑 Description
Se modifico el como se muestra el feedback
![image](https://github.com/user-attachments/assets/cffe6ca4-2a40-446a-b9bb-075db5a2bc0a)

## ✅ Checks

- [ ] My pull request adheres to the code style of this project
- [ ] My code requires changes to the documentation
- [ ] I have updated the documentation as required
- [ ] All the tests have passed

## ℹ Additional Information

2024-07-27 19:38 UTC, JamiltonQuintero requested changes
Saludos Reyporfa revisa los comentarios

2024-07-27 19:38 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +  // @ViewChild('carouselContainer')
Remover codigo comentado

2024-07-27 19:38 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +    navText: [
Evitar codigohtmlen ts. Si esto puede ir con ng if dentro del html mejor

2024-07-27 19:38 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +            this.renderer.setStyle(
Se esta manipulando mucho el html y los estilos desde el ts y esto puede generasr problemas en el DOM cuando se quiere reenderizar la aplicacion. Es mejor tenerlo estatico y precargado. Y hacer los cambios con ng ifs

2024-07-27 19:38 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +        //this.animateCarousel();
Remover comentarios

2024-07-27 19:38 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +  //     }
Remover comentarios

2024-07-27 22:44 UTC, DylanSerkovich commented on src/app/components/zona-entrevista/multipasos/paso-4/paso-4.component.ts
> +    navText: [
los iconos es lo único que si es necesario cargarlo mediante los options al renderizar el carousel

2024-07-28 16:40 UTC, JamiltonQuintero approved these changes

2024-07-28 17:04 UTC, merged