Feature/70040038 - Mejorar el mensaje de la zona de espera.
EntrevistadorInteligente/si-client-app pull request #77
Opened 2024-08-06 06:51 UTC by crisdevcode

- Se agregan gif animations a la zona de espera.
- Se deshabilita el envío de alertas de confirmación al momento de generar la entrevista y el feedback (paso 2 y 3) ya que bloquea la visualización de los gifs.

![Screenshot](https://github.com/user-attachments/assets/b00e6525-9d86-4f0e-b7f5-a1539de28878)

2024-08-06 16:10 UTC, JamiltonQuintero commented
jajajjaja te amoooooooo desplegado inmediato

2024-08-06 16:58 UTC, JamiltonQuintero requested changes

2024-08-06 16:58 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-2/paso-2.component.ts
> +          // this.alert('Éxito', 'Solicitud entrevista enviada con éxito, se está generando tu entrevista', 'success');
Si no vamos a mostrar el modal removamos el codigo comentado

2024-08-06 16:58 UTC, JamiltonQuintero commented on src/app/components/zona-entrevista/multipasos/paso-3/paso-3.component.ts
> +        // this.alert('Éxito', 'Entrevista enviada con éxito, se está generando el feedback', 'success');
Igual

2024-08-06 17:32 UTC, crisdevcode commented on src/app/components/zona-entrevista/multipasos/paso-2/paso-2.component.ts
> +          // this.alert('Éxito', 'Solicitud entrevista enviada con éxito, se está generando tu entrevista', 'success');
Código removido.

2024-08-06 17:33 UTC, crisdevcode commented on src/app/components/zona-entrevista/multipasos/paso-3/paso-3.component.ts
> +        // this.alert('Éxito', 'Entrevista enviada con éxito, se está generando el feedback', 'success');
Código removido.

2024-08-07 04:12 UTC, JamiltonQuintero approved these changes, later dismissed

2024-08-07 05:10 UTC, JamiltonQuintero approved these changes

2024-08-07 05:11 UTC, merged