Feature/74340576 - Sincronización de notificaciones & zona de espera.
EntrevistadorInteligente/si-client-app pull request #82
Opened 2024-08-10 23:01 UTC by crisdevcode

- Se sincronizan las notificaciones y la zona de espera con el objetivo de reemplazar la animación de espera por una animación de éxito.
- Se realizan algunos ajustes al componente de notificaciones.

![ss-success](https://github.com/user-attachments/assets/4c1f258a-96c8-4ccb-bce9-5b7b47b622b3)

2024-08-11 04:49 UTC, MranDvX approved these changes
aprobado

2024-08-11 04:58 UTC, MranDvX requested changes
se queda colgado y no cambia el gif cuando se genera la notificación. si lo puedes mirar nuevamente

2024-08-11 16:59 UTC, crisdevcode commented
> se queda colgado y no cambia el gif cuando se genera la notificación. si lo puedes mirar nuevamente

Qué extraño. Acabo de probarlo y sigue funcionando. Intenta limpiar caché o probar en modo incógnito. También asegúrate de estar accediendo a **localhost:4200/es/entrevistas** y no a **pruebas-entrevistador-inteligente.site/es/entrevistas** porque por defecto te hace la redirección hacia pruebas.

https://github.com/user-attachments/assets/4bc1dc48-dc3f-4de1-bc2b-6d57997ef16d

2024-08-18 05:32 UTC, JamiltonQuintero commented
Revisando probabelmente fue algo de dev.

2024-08-22 02:30 UTC, JamiltonQuintero commented
APROBADISIMO

2024-08-22 02:31 UTC, merged